version: "3.5"
services:
    docker_test_app:
        image: workshopregistry.azurecr.io/dockertestapp:v1.0.0
        container_name: docker_test
        deploy:
            replicas: 2
            resources:
                limits:
                    cpus: "0.25"
                    memory: "50M"
            restart_policy:
                condition: "on-failure"
        ports:
            - "9005:7005"
        networks:
            - default
networks:
    default:
        name: compose_network

        